version: '3'

services:
  animals_db:
    image: mysql:8.0.31
    container_name: animals_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=test
    volumes:
      - animals_dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
volumes:
  animals_dbdata:

networks:
  app-network:
    driver: bridge